switch command now uses fzf

diff --git a/bash/bash_functions_work b/bash/bash_functions_work
--- a/bash/bash_functions_work
+++ b/bash/bash_functions_work
@@ -40,37 +40,49 @@ clippy_installer () {
 }
 export clippy_installer
 
+
+
 unset -f switch
-switch () {
-    LASTPASS_EMAIL='deac.karns@gmail.com'
-    PROFILE=$(clippy aws sso assume)
-    if [ $? -eq 0 ]
+switch() {
+    if ! command -v fzf &> /dev/null
     then
-        export AWS_PROFILE=$PROFILE
-        export AWS_DEFAULT_PROFILE=$PROFILE
-        export AWS_EB_PROFILE=$PROFILE
-
-        # If you are switching to an ENG account it wont use SSO
-        USE_SSO=`aws configure get sso_start_url --profile $PROFILE`
-        if [ -z "${USE_SSO}" ]
+        # If Fuzzy Find (FZF) isnt installed, lets use clippy
+        local PROFILE=$(clippy aws sso assume)
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
+    else
+        # if Fuzzy Find is installed, lets use that because its better
+        PROFILE=$(aws configure list-profiles | fzf --prompt "Select profile: ")
+        if [ -z "${PROFILE}" ]
         then
-            LASTPASS_STATUS=`lpass status`
+            return 1
+        fi
+    fi
 
-            if [ "$LASTPASS_STATUS" == "Not logged in." ]; then
-                echo "Authenticating with LastPass"
-                lpass login --trust $LASTPASS_EMAIL
-            else
-                echo "LastPass authenticated"
-            fi
-            clippy okta login --factor okta
+    # Set the AWS Profile variables
+    export AWS_DEFAULT_PROFILE=$PROFILE
+    export AWS_PROFILE=$PROFILE
+    export AWS_EB_PROFILE=$PROFILE
+    export AWS_PROFILE_REGION=$(aws configure get region)
+
+    # Determine if this is an SSO login
+    USE_SSO=`aws configure get sso_start_url --profile $PROFILE`
+
+    if [ -z "${USE_SSO}" ]
+    then
+        # This is not an SSO login
+        clippy okta login --factor okta
+    else
+        # Check SSO login validity
+        SSO_ACCOUNT=$(aws sts get-caller-identity --query "Account" --output text)
+
+        if [ ${#SSO_ACCOUNT} -eq 12 ];  then
+            echo "AWS SSO session valid" ;
         else
-            SSO_ACCOUNT=$(aws sts get-caller-identity --query "Account" --output text)
-            if [ ${#SSO_ACCOUNT} -eq 12 ];  then
-                echo "AWS SSO session valid" ;
-            else
-                echo "AWS SSO session invalid"
-                aws sso login
-            fi
+            echo "AWS SSO session invalid"
+            # Open an SSO login window
+            aws sso login
         fi
     fi
 }
